
export namespace Airmail3 {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Airmail App
  */
 export interface Application {
   /**
    * selected message url
    */
   selectedMessageUrl(): string;
   /**
    * current selected message
    */
   selectedMessage(): any;
   /**
    * List of messages currently selected
    */
   selectedMessages(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface OutgoingMessage {
   /**
    * The unique identifier.
    */
   id(): string;
   /**
    * the item's name
    */
   name(): string;
   /**
    * Subject of the email
    */
   subject(): string;
   /**
    * Sender of the message
    */
   sender(): string;
   /**
    * The content of the message
    */
   content(): string;
   /**
    * The HTML content of the message
    */
   htmlContent(): string;
   /**
    * Signature of the message
    */
   signature(): string;
   /**
    * The HTML signature of the message
    */
   htmlSignature(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Recipient
  */
 export interface Recipient {
   /**
    * Email of the recipient
    */
   address(): string;
   /**
    * Name of the recipient
    */
   name(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Recipient of the To Field
  */
 export interface ToRecipient {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Recipient of the Cc field
  */
 export interface CcRecipient {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Recipient of the Bcc field
  */
 export interface BccRecipient {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An attachment
  */
 export interface Attachment {
   filename(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Recipient of the Attachment field
  */
 export interface MailAttachment {}
    
    // CLass Extension
    
    // Records

    // Function options



}
export interface Airmail3 extends Airmail3.Application {
    // Functions

     /**
      * send message
      * @param directParameter outgoing message
      * 
      */
     sendmessage(directParameter: {}, ): void;

     /**
      * open the message composer
      * @param directParameter outgoing message
      * 
      */
     compose(directParameter: {}, ): void;

     /**
      * Look up a string, searches for messages
      * @param directParameter The string to lookup
      * @return searched messages
      */
     lookup(directParameter: {}, ): any;
}
