
export namespace GarageBand {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The top level scripting object.
  */
 export interface Application {}
    
    // CLass Extension
    
    // Records

    // Function options

}
export interface GarageBand extends GarageBand.Application {
    // Functions

     /**
      * Render an iLife Preview for a project
      * @param directParameter Reference to the project
      * 
      */
     renderPreview(directParameter?: any, ): void;
}
