
export namespace iAWriter {
    // Default Application
 export interface Application {}
    // Class
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface Document {}
    
    // Records

    // Function options

}
export interface iAWriter extends iAWriter.Application {
    // Functions

}
